name: mtlora
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - addict=2.4.0=pyhd8ed1ab_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cpp-expected=1.1.0=hff21bea_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - fmt=11.1.4=h07f6e7f_1
  - freetype=2.13.3=ha770c72_1
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - icu=75.1=he02047a_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgomp=15.1.0=h767d61c_3
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.7.2=h09b5827_2
  - libmagma_sparse=2.7.2=h09b5827_3
  - libmamba=2.3.0=h44402ff_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.50=h943b412_0
  - libprotobuf=4.24.4=hf27288f_0
  - libsolv=0.7.33=h7955e40_0
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.7=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - magma=2.7.2=h4aca40b_3
  - mamba=2.3.0=h233bd08_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2022.2.1=h6508926_16999
  - mmcv=2.0.0=cuda112py38hf760a72_200
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.1=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=he02047a_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=7_cp38
  - pytorch=2.0.0=cuda118py38hde7dd16_304
  - readline=8.2=h8c095d6_2
  - regex=2024.7.24=py38h2019614_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - simdjson=3.13.0=h84d6215_0
  - sleef=3.8=h1b44611_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_hd72426e_102
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.0.1
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cmake==3.25.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - easydict==1.10
      - einops==0.4.1
      - filelock==3.12.0
      - fonttools==4.57.0
      - fsspec==2023.5.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.4
      - imageio==2.31.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.2
      - lit==15.0.7
      - matplotlib==3.7.5
      - mmcls==0.25.0
      - mmengine==0.7.4
      - mmsegmentation==1.0.0
      - numpy==1.24.1
      - opencv-python==4.7.0.72
      - pillow==10.2.0
      - prettytable==3.11.0
      - psutil==7.0.0
      - ptflops==0.7
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0
      - requests==2.28.1
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.16.0
      - termcolor==2.3.0
      - tifffile==2023.4.12
      - timm==0.9.2
      - tokenizers==0.15.2
      - tomli==2.2.1
      - torch==2.0.1+cu117
      - torchaudio==2.0.2+cu117
      - torchvision==0.15.2+cu117
      - tqdm==4.65.0
      - transformers==4.36.2
      - triton==2.0.0
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/su01/miniconda3/envs/mtlora
